export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";

export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET";

export const REMOVE_PRODUCT_BASKET = "REMOVE_PRODUCT_BASKET";

export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY";

export const INCREASE_PRODUCT_QUANTITY = "INCREASE_PRODUCT_QUANTITY";

export const CLEAR_BASKET = "CLEAR_BASKET";

export const GET_PRODUCTS_DB = "GET_PRODUCTS_DB";
